language: node_js
node_js:
  - "node"
  - "7"
  - "6"
  - "5"

before_script:
  - node_modules/.bin/tslint -c tslint.json 'src/*.ts'
  - node_modules/.bin/tsc
  - node_modules/.bin/mocha test

+notifications:
  email:
    on_success: change
    on_failure: always 
